### ISSUE TITLE
HTTP/2 doesn't require HTTPS

### ISSUE THREAD

**Issue by ericandrewlewis** [ericandrewlewis/say-yes-to-https#14]
@mholt brought up a good point in #13:

> Technically, HTTP/2 can be served with plaintext HTTP, but nobody is doing that.

The text we have regarding HTTP/2 is in the list of extra benefits of using HTTPS:

> Speed. HTTP/2 can deliver your website to browsers quicker. HTTP/2 can only be used with HTTPS.

@mholt suggests changing it to:

> Speed. HTTP/2 can deliver your website to browsers quicker. HTTP/2 is only used with HTTPS.

There's a line of brevity and technical precision to walk here. We want people to understand that because browsers require HTTPS for HTTP/2, HTTPS is a practical requirement, even if the HTTP/2 spec and non-browser implementations don't require it.

How about:

> Speed. HTTP/2 can deliver your website to browsers quicker. Browsers require HTTPS to use HTTP/2.

**Comment by mholt** [comment]
SGTM :+1:
