### ISSUE TITLE
HTTPS Error for Project Website

### ISSUE THREAD

**Issue by pmacMaps** [ericandrewlewis/say-yes-to-https#20]
Your website is throwing an error in Chrome related to HTTPS.

![irony-https](https://cloud.githubusercontent.com/assets/12861454/24010093/455c8c50-0a4d-11e7-8677-0f0532f9bede.PNG)

**Comment by ericandrewlewis** [comment]
Oh the irony. Thanks for letting me know, updated it 😄

**Comment by ericandrewlewis** [comment]
This has been fixed
