### ISSUE TITLE
Adding Surge.sh to the guide?

### ISSUE THREAD

**Issue by kennethormandy** [ericandrewlewis/say-yes-to-https#6]
Hey, this is an awesome resource, thanks for putting it together!

I think we will link to this in the [Surge.sh](https://surge.sh) docs, which I work on. I was wondering if you’d be interested in a PR that adds some information about Surge supports SSL?

We do charge for SSL so I wanted to ask about this first—I know this is more of a general reference, but in the same way SSLMate provides a developer friendly way to get certs, we are working on continuing to make it easier for developers to add SSL to their static sites and client side apps.
- [Adding an SSL cert on Surge](https://surge.sh/help/securing-your-custom-domain-with-ssl) using `surge ssl`
- [Forcing HTTPS redirects](https://surge.sh/help/using-https-by-default)
- We also offer free HTTPS for _surge.sh_ subdomains
- Also working on HSTS headers https://github.com/sintaxi/surge/issues/165#issue-118719633 and getting Let’s Encrypt integrated once it’s ready

Let me know what you think! Either way, nice to know where to point people for a general introduction to the topic, thanks for your work on that.

**Comment by ericandrewlewis** [comment]
Hi @kennethormandy, I'm glad this project seems useful even in its early stages!

The first line in the [HTTPS setup guide](https://sayyestohttps.org/how-to-setup-https/) suggests folks to ask their hosting provider for how to setup HTTPS. We can be more proactive with that suggestion by linking to various hosting providers HTTPS docs on a dedicated page. Does that sound good?

**Comment by kennethormandy** [comment]
Yeah that sounds appropriate! I’ve got a note to update our SSL docs with links to your project now too.

**Comment by ericandrewlewis** [comment]
Cool! I added the links you provided in 193917f. If you'd like to modify them at all now or later as things come up, feel free to open a PR!
