### ISSUE TITLE
Add integrity to the list of benefits of using HTTPS

### ISSUE THREAD

**Issue by ericandrewlewis** [ericandrewlewis/say-yes-to-https#9]
@MacLemon suggested in #7:

> [We should add] integrity and a small explanation of it to the benefits of using HTTPS.

**Comment by MacLemon** [comment]
A stub is already one of my pull requests. Integrity is a key benefit of using HTTPS. It prevents MITM from injecting Ads or tracking cookies into your site, or manipulate content.

Many ISPs, especially phone carriers, are known to add tracking cookies and “optimize” images and javascript for mobile devices to reduce data transmissions, while often also breaking sites while doing that. 

Usually one doesn't want someone else being able to support their shady business by adding or changing things on your website.

**Comment by ericandrewlewis** [comment]
Fixed in 056ec73c2c16c27e63e08e3c10ef9895d9d7e2e1. Thanks!
